Feature auth
competitivebidding/backend pull request #1
Opened 2023-04-02 18:41 UTC by MalinavyBusel

2023-04-02 21:32 UTC, vstaran requested changes

2023-04-02 21:32 UTC, vstaran commented on src/users/users.controller.ts
>      const password_ = await encodePassword(userData.password);
почему так странно назвал переменую password_ ?

2023-04-02 21:32 UTC, vstaran commented on src/users/users.controller.ts
> +  @Post('login')
@post('login') - нужно перенести в auth

2023-04-02 21:32 UTC, vstaran commented on src/users/users.controller.ts
> +  async addUser(@Body() userData: UserModel): Promise<string> {
Эта функция странная  создает пользователя и дает ключ авторизации - когда такое нужн будет ?

2023-04-02 21:32 UTC, vstaran commented on src/Utils/auth.ts
- переименовать папку в auth. А auth.ts - это наверно module сделать.
- созать controller с нужными endpoints

2023-04-02 21:32 UTC, vstaran commented on src/users/users.controller.ts
> +  async login(@Body() userCredentials: UserModel): Promise<string> {
userCredentials: UserModel - для авторизации нужно только логин и пароль а не вся модель user (сейсам там пару полей, но туда нужно будет добавить много полей)

2023-04-02 21:32 UTC, vstaran commented on src/users/users.controller.ts
> +      throw new UnauthorizedException('Invalid user credentials');
Если это Rest API по правильному нужно возвращать код 401 и json сообщение.

2023-04-02 21:32 UTC, vstaran commented on src/Utils/auth.ts
+ добавить Guards
вот тут есть инструкция, пример
https://docs.nestjs.com/security/authentication

2023-04-03 11:02 UTC, MalinavyBusel commented on src/users/users.controller.ts
> +      throw new UnauthorizedException('Invalid user credentials');
Оно вроде так и делает, я постманом смотрел

2023-04-03 11:02 UTC, MalinavyBusel commented on src/users/users.controller.ts
> +      throw new UnauthorizedException('Invalid user credentials');
только сообщение строкой

2023-04-04 14:49 UTC, MalinavyBusel commented on src/users/users.controller.ts
> +  @Post('login')
перенес

2023-04-04 14:49 UTC, MalinavyBusel commented on src/Utils/auth.ts
Эндпоинт добавил, гард еще буду делать

2023-04-04 14:50 UTC, MalinavyBusel commented on src/users/users.controller.ts
> +  async login(@Body() userCredentials: UserModel): Promise<string> {
моделька в контроллере лежит, точнее интерфейс

2023-04-05 09:43 UTC, merged