Feature forgot password
competitivebidding/backend pull request #10
Opened 2023-05-04 06:47 UTC by BadVoice

Sorry i'm dumb forever ;) 
my first baby is poop XD

2023-05-04 07:22 UTC, vstaran requested changes

2023-05-04 07:22 UTC, vstaran commented on .env.example
> +MAIL_PASS="ZdEQcqudfdhUuHuPv0gU"
Доступы нельзя выкладывать в публичный доступ. нужно было отправить пароль и логин в приват.

2023-05-04 07:22 UTC, vstaran commented on src/auth/auth.resolver.ts
> +    @Post()
`@Post()` Это не нужно.

2023-05-04 07:22 UTC, vstaran commented on src/auth/auth.service.ts
> +        await this.prisma.user.update({
тут нужно использовать `this.userService`

2023-05-04 07:22 UTC, vstaran commented on src/mail/templates/verify-code.hbs
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
Это все удали слелай просто все через `<p>Текст</p>`

2023-05-04 07:22 UTC, vstaran commented on src/mail/mail.service.ts
> +                html: `<p>You're confirmation code ${confirmationCode}</p>`,
если используешь template то зачем тогда етот html ?

2023-05-04 07:22 UTC, vstaran commented on src/mail/mail.service.ts
> +    async sendForgotPasswordEmail(userEmail: string, confirmationCode: string): Promise<void> {
вместо confirmationCode: string - может сразу использовать context обєкт с нужными значениями.

2023-05-04 07:22 UTC, vstaran commented on prisma/schema.prisma
> +generator client {
Осторожно с этим фалом. я вижу ты в него добавил просто одно поле ну и полностю переформатирол его, старайся больше так не делать. Если еще ктото внесет в него изменения то потом смержить их будет сложно.

2023-05-04 07:22 UTC, vstaran commented on src/auth/auth.service.ts
> +            message: 'password_forgot',
почему тут возвращается это ?

2023-05-04 07:22 UTC, vstaran commented on src/auth/auth.service.ts
> +            throw new ForbiddenException('User_not_found')
просто пиши "User not found" без underscore

2023-05-04 07:22 UTC, vstaran commented on src/auth/dto/forgot-password.ts
> +    email: string
добавить проверку что это Емейл

2023-05-04 07:22 UTC, vstaran commented on src/mail/mail.module.ts
> +                    from: 'No Reply - project@name.com',
это тоже вынести в env

2023-05-04 07:22 UTC, vstaran commented on src/mail/mail.service.ts
> +    async sendForgotPasswordEmail(userEmail: string, confirmationCode: string): Promise<void> {
посмотрел примеры реализации. оставляем как есть.

2023-05-04 07:31 UTC, BadVoice commented on .env.example
> +MAIL_PASS="ZdEQcqudfdhUuHuPv0gU"
I did it, thx

2023-05-04 07:31 UTC, BadVoice commented on src/auth/auth.resolver.ts
> +    @Post()
I did it, thx )

2023-05-04 07:35 UTC, BadVoice commented on src/mail/mail.service.ts
> +                html: `<p>You're confirmation code ${confirmationCode}</p>`,
Correct, i deleted it XD

2023-05-04 07:51 UTC, BadVoice commented on src/auth/auth.service.ts
> +        await this.prisma.user.update({
Сделал

2023-05-04 07:51 UTC, BadVoice commented on src/mail/templates/verify-code.hbs
> +<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
Сделал черновой вариант через теги

2023-05-04 07:52 UTC, BadVoice commented on prisma/schema.prisma
> +generator client {
Хорошо, буду уточнять у тебя по поводу него

2023-05-04 07:55 UTC, BadVoice commented on src/auth/auth.service.ts
> +            throw new ForbiddenException('User_not_found')
Ого, это underscore называется)

2023-05-04 07:56 UTC, BadVoice commented on src/auth/dto/forgot-password.ts
> +    email: string
Сначала сделал @IsEmail(), потом удалил и забыл.
Исправил

2023-05-04 07:58 UTC, BadVoice commented on src/mail/mail.module.ts
> +                    from: 'No Reply - project@name.com',
Хорошо

2023-05-04 07:58 UTC, BadVoice commented on src/auth/auth.service.ts
> +            message: 'password_forgot',
вернул юзера (email)

2023-05-04 11:34 UTC, vstaran approved these changes

2023-05-04 20:39 UTC, Elias0Ainsworth approved these changes

2023-05-06 10:54 UTC, MalinavyBusel approved these changes

2023-05-07 21:11 UTC, merged