Feature chat
competitivebidding/backend pull request #11
Opened 2023-05-06 10:40 UTC by Elias0Ainsworth

2023-05-06 14:39 UTC, vstaran requested changes

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.resolver.ts
> +    async updateMessage(@GetCurrentUser() user: JwtPayload, dto: MessageUpdateInputType): Promise<Message> {
Если тебе нужна прост userId там есть @GetCurrentUserId()

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +    async sendMessage(dto: NewMessageInputType, userId): Promise<Message> {
тут тоже нужно както проверить что пользователю можно создавать сообщения в комнате.

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/dto/room-update.input.ts
> +    owner?: number
ownerId - просто owner - очень абстрактно

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/entities/room.entity.ts
> +    owner: number
``ownerId``

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async getRoomByTitle(@Args('title') title: string): Promise<Room[]> {
зачем вообще такая функция getRoomByTitle ? если нужен поиск нужно сделать более общую фунцию

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +export class RoomResolver {
@GetCurrentUser() - можно заменить на @GetCurrentUserId()

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async getAllRooms(): Promise<Room[]> {
Тут нужно будет посмотреть нужно ли нам давать в публичный доступ все чаты. Но даже если убрать публичный доступ, то я думаю всеравно чаты будут приватными между пользователями.

Вообщем нужно записать себе вопросик к фронтендерам. как им сделать. ну или оставить просто они или реализую данный функциона, а может и нет.

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +    async validateUser(id: number, userId: number) {
Заметил что у тебя в service-ах проверки - как потом выводить по таким проверка ошибки для польщзователя ?

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +    async findUserMessagesInRoom(userId: number, roomId: number): Promise<Message[]> {
Используй тут для параметров Prisma Input - можно сделать более униварсальную функцию.

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +        return null
может вернуть null но функция ждет Promise<Message>

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +        if (this.validateUser(id, userId)) {
Для удаления можно и не проверять есть или та строчка которую ты удаешь. delete вертает удаленый обект. И тут параметры как Prisma Input использовать

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +    async getAllMessagesInRoom(roomId: number): Promise<Message[]> {
можно назвать `getAllMessagesByRoomId` - более точно и с метода понятно что ей нужно дать как параметр и что она вернет.

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/entities/room.entity.ts
> +    description: string
```typescript
description?: string
```
 - необезательное

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async getRoomByTitle(@Args('title') title: string): Promise<Room[]> {
и дать фронту выбор искать и по title и по description - использовать Prisma Where Input

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async getAllUsersInRoom(@Args('roomId') roomId: number): Promise<User[]> {
getAllUsersByRoomId

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.service.ts
> +    async getRoomById(id: number): Promise<Room> {
`Promise<Room | null>`

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async joinUserRoom(@GetCurrentUser() user: JwtPayload, @Args('roomId') roomId: number): Promise<User> {
Зачем тут возвращать пользователя ?  логично вернуть рум. ну или уже какойто обект с success = true|false

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.service.ts
> +    async getAllUserRooms(userId: number): Promise<Room[]> {
`getAllRoomsByUserId`

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.service.ts
> +    async getAllUsersInRoom(roomId: number): Promise<User[]> {
`getAllUsersByRoomId`

2023-05-06 14:39 UTC, vstaran commented on src/chat/room/room.service.ts
> +        const rooms = await this.prisma.userInRoom.findMany({ where: { userId }, select: { room: true } })
тут нужно сделать что то вроде такого:

```typescript
const rooms = await this.prisma.room.findMany({
  where: {
    users: {
      some: {
        id: userId
      }
    }
  }
});
```

и тогда не нужно переберать еще раз весь полученый масив map-ом.
вообще нужно старатся сделать такие запросы чтобы потом не нужно было их дополнительно фильтровать или еще както обрабатывать. так как база сделает это быстрее.

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.resolver.ts
> +        @GetCurrentUser() user: JwtPayload,
а зачем тут user если он не используется ? или ты запушыл с 1 - тестировал ?

2023-05-06 14:39 UTC, vstaran commented on src/chat/message/message.service.ts
> +export class MessageService {
В service используй Prisma.MessageWhereUniqueInput и т.д. для аргументов. Prisma их там нагенерировала их и нужно использовать.

2023-05-06 16:41 UTC, vstaran requested changes

2023-05-06 16:41 UTC, vstaran commented on src/chat/message/message.resolver.ts
> +    @Query(() => [Message])
Если метод может вернуть null - нужно ``@Query(() => [Message], { nullable: true })``

2023-05-06 18:37 UTC, MalinavyBusel reviewed
Мы так и не начали писать комменты к своему коду, это не оч хорошо

2023-05-06 18:37 UTC, MalinavyBusel commented on prisma/schema.prisma
> +  updatedAt DateTime @updatedAt
Если будет время и желание, можно еще явно onUpdate и onDelete прописать

2023-05-06 18:37 UTC, MalinavyBusel commented on src/chat/room/room.service.ts
> +                owner: data.owner,
Тут ownerId или какое-то другое поле? Если id, то, как Виктор уже писал выше, лучше поменять имя.

2023-05-06 18:37 UTC, MalinavyBusel commented on src/chat/message/dto/findUserMessagesInRoom.input.ts
> +export class FindUserMessagesInRoomInputType {
Может лучше просто userMessages или типа такого? Ну просто итак понятно, что если сообщения юзера, то из конкретной комнаты. Типа зачем нам все его сообщения в целом?

2023-05-07 06:34 UTC, vstaran requested changes

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/room.service.ts
> +    async getRoom(where: Prisma.RoomWhereInput): Promise<Room[]> {
``getRooms`` - findMany

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/message.resolver.ts
>      async getAllMessagesInRoom(@Args('roomId') roomId: number): Promise<Message[]> {
`getAllMessagesByRoomId`

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async getRoom(@Args('dto') dto: RoomFindManyInputType): Promise<Room[]> {
`getRooms` - [Room] - масив!

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/room.resolver.ts
> +    async leftUserRoom(@GetCurrentUserId() userId: number, @Args('roomId') roomId: number): Promise<User> {
left - прошлое. получается список тех кто покинул ?
`leaveUserRoom` или `leaveUserFromRoom`

а так как тут не нужно указывать userId то можно просто `leaveFromRoom`

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/room.service.ts
> +        return await this.prisma.user.findMany({ where: { roomId: { some: { roomId } } } })
проверял оно работает ?
``this.prisma.user.findMany({ where: { room: { some: { roomId } } } })``

P.S. оставил коментарий на prisma shema - там нужно изменить roomId

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/room.service.ts
> +        return await this.prisma.room.findMany({ where: { userId: { some: { userId } } } })
проверял оно работает ?
``this.prisma.room.findMany({ where: { user: { some: { userId } } } })``

P.S. оставил коментарий на prisma shema - там нужно изменить userId

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/dto/room-findMany.input.ts
> +export class RoomFindManyInputType {
имя файла `room.input.ts`
class `RoomInput`

у тебя `RoomFindManyInputType` - а если нужно будет найти одну комнату по заголовку и описанию ты будешь создавать новий InputType - назвешь его `RoomFindOneInputType` и внутри он будет идентичный к  `RoomFindManyInputType` ?

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/dto/user-messages.input.ts
> +export class UserMessages {
имя файла `message.input.ts`
class `MessageInput`

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/message.resolver.ts
> +    async findUserMessagesInRoom(@Args('dto') dto: UserMessages): Promise<Message[]> {
`getAllUserMessages`

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/dto/room-update.input.ts
> +export class RoomUpdateInputType {
`RoomUpdateInput`

2023-05-07 06:34 UTC, vstaran commented on src/chat/room/dto/room.input.ts
> +export class RoomInputType {
`RoomInput`

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/dto/message-update.input.ts
> +export class MessageUpdateInputType {
`MessageUpdateInput`

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/dto/new-message.input.ts
>  export class NewMessageInputType {
`NewMessageInput`

2023-05-07 06:34 UTC, vstaran commented on prisma/schema.prisma
> +  roomId    UserInRoom[]
`rooms UserInRoom[]` - по примеру как с остальными, например `payments UserPayment[]`
в таблице нет поля roomId - вводит в заблуждение

2023-05-07 06:34 UTC, vstaran commented on prisma/schema.prisma
> +  userId      UserInRoom[]
`users UserInRoom[]` - тоже самое что и с комнатами

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/message.service.ts
> +    async validateUser(id: number, userId: number) {
что по етому пункту - так и не заметил что ты на него както отреагировал ?

2023-05-07 06:34 UTC, vstaran commented on prisma/schema.prisma
>    description String        @default("null")
вместо
`description String @default("null")`

нужно:
`description? String`

2023-05-07 06:34 UTC, vstaran commented on src/chat/message/message.resolver.ts
>      async getAllMessagesInRoom(@Args('roomId') roomId: number): Promise<Message[]> {
И получается что ето дубль метода `findUserMessagesInRoom` - с его помощю можно витащить сообщения пользователя в комнате.

2023-05-08 18:36 UTC, BadVoice commented
> Мы так и не начали писать комментарии к собственному коду, это не очень хорошо

Мне кажется если заполнять проект комментариями, то нужно их поддерживать-обновлять, так что наверно лучше стремиться к self documenting code

2023-05-09 16:50 UTC, merged