Feature auction
competitivebidding/backend pull request #7
Opened 2023-04-25 16:07 UTC by MalinavyBusel

2023-04-25 16:19 UTC, vstaran commented on prisma/schema.prisma
> +  name     String    @unique
имя статуса не обьязательно должно быть уникально.

2023-04-25 16:37 UTC, vstaran requested changes

2023-04-25 16:37 UTC, vstaran commented on src/auctions/auctions.resolver.ts
> +    async deleteAuction(@Args('where') where: AuctionUniqueInput) {
Зачем хотель на вход весь where если тебе нужна просто id ?
@Args('id', { type: () => Int }) id: number
const auction = await this.auctionsService.getAuctionById(id)

или уже дава удалять по всему where - но так наверно не нужно.

2023-04-25 16:37 UTC, vstaran commented on src/auctions/auctions.resolver.ts
> +    async updateAuction(@Args('where') where: AuctionUniqueInput, @Args('data') data: AuctionInput) {
Зачем хотель на вход весь where если тебе нужна просто id ?
@Args('id', { type: () => Int }) id: number
const auction = await this.auctionsService.getAuctionById(.id)

2023-04-25 16:37 UTC, vstaran commented on src/auctions/auctions.resolver.ts
> +            startedAt: data.startedAt || auction.startedAt,
Если данные не переданы просто не обновляй их - тоесть нужно сделать так чтобы они не передавались в сервис вообще.

обновляй только то что дают.

2023-04-25 16:37 UTC, vstaran commented on src/auctions/auctions.resolver.ts
> +    async updateAuction(@Args('where') where: AuctionUniqueInput, @Args('data') data: AuctionInput) {
посмотри пример как я слелал updateNews

2023-04-25 16:37 UTC, vstaran commented on src/auctions/dto/auction.create.ts
> +    @IsString()
статус должен передаватся имено id

2023-04-25 16:37 UTC, vstaran commented on src/auctions/dto/auction.input.ts
> +    @IsString()
статус не опциональный он долженбыть полубому. + еще нужно добавить в призму значение статуса в Аукциона по умолчанию. (всегда первый, а первый у нас будет Новый, нужно определится с списком статусов)

2023-04-25 16:37 UTC, vstaran commented on src/auctions/dto/auction.input.ts
> +    @IsOptional()
Зачем тогда статусНейм ?

2023-04-25 16:37 UTC, vstaran commented on src/bids/bids.resolver.ts
> +    async updateBid(@Args('where') where: BidUniqueInput, @Args('data') data: BidUpdateInput) {
тут тоже самое что и с Аукционом с where

2023-04-25 16:57 UTC, vstaran requested changes

2023-04-25 16:57 UTC, vstaran commented on src/bids/bids.resolver.ts
> +        return this.bidsService.deleteBid(where)
await пропустил

2023-04-25 16:57 UTC, vstaran commented on src/bids/bids.service.ts
> +            include: {
зачем при удалении делать выробку по соседним таблицам не понятно!

2023-04-25 16:57 UTC, vstaran commented on src/bids/bids.service.ts
> +            include: {
убрать

2023-04-25 16:57 UTC, vstaran commented on src/bids/bids.resolver.ts
> +        const bid = await this.bidsService.createBid({
почему не можно было написать просто ?
const bid = await this.bidsService.createBid(data)

просто потом когда добавится еще поле то нужно будет его добавлять не только в BidCreateInput, но еще и сюда вписать. Причем тут никаких операций над полем не делается оно тут просто вписывается.

2023-04-25 16:57 UTC, vstaran commented on src/auctions/auctions.service.ts
> +            include: {
убрать

2023-04-25 16:57 UTC, vstaran commented on src/auctions/auctions.service.ts
> +            include: {
убрать

2023-04-25 16:57 UTC, vstaran commented on src/auctions/auctions.resolver.ts
> +        const auction = await this.auctionsService.createAuction({
почему не можно было написать просто ?
const auction = await this.auctionsService.createAuction(data)

просто потом когда добавится еще поле то нужно будет его добавлять не только в AuctionCreateDto, но еще и сюда вписать. Причем тут никаких операций над полем не делается оно тут просто вписывается.

+ для ставок ты назвал BidCreateInput а тут почемуто AuctionCreateDto 
там Input  а там Dto. нужно определится!

2023-04-26 05:56 UTC, MalinavyBusel commented on src/auctions/dto/auction.input.ts
> +    @IsString()
пока убирать не буду, мне кажется, что в основном AuctionInput будет для where использоваться, а там это поле может быть в условии, а может и нет.

2023-04-26 08:30 UTC, vstaran approved these changes

2023-04-26 21:23 UTC, merged